wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: $ip_address
    gateway: !secret gateway
    subnet: !secret subnet
    dns1: !secret dns1
    dns2: !secret dns2
  ap:
    ssid: $device_name-$device_model
    password: !secret fallback_ap_password

  reboot_timeout: 5min

# Enable Home Assistant API
api:
  encryption:
      key: !secret api_password
  reboot_timeout: 5min

# Enable over-the-air updates
ota:
  platform: esphome
  password: !secret ota_password

# Enable Web server
web_server:
  port: 80

time:
  - platform: sntp
    id: sntp_time
    timezone: America/Denver
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - 2.pool.ntp.org

# Text sensors with general information
text_sensor:
  - platform: version
    name: $friendly_name version
  - platform: wifi_info
    ip_address:
      name: $friendly_name ip
    ssid:
      name: $friendly_name ssid
    bssid:
      name: $friendly_name bssid

sensor:
  # Uptime sensor
  - platform: uptime
    name: $friendly_name uptime
  # WiFi Signal sensor
  - platform: wifi_signal
    name: $friendly_name wifi signal
    update_interval: 10s
