---
substitutions:
  device_model: maxcio

esp8266:
  restore_from_flash: false

light:
  - platform: status_led
    disabled_by_default: true
    id: status_1
    internal: true
    name: "Status LED"
    pin:
      inverted: true
      number: GPIO13

binary_sensor:
  - platform: gpio
    filters:
      - delayed_off: 10ms
      - invert:
    id: button_1
    internal: true
    name: Button
    on_press:
      - fan.toggle: fan_1
    pin: GPIO00
    restore_mode: ALWAYS_OFF

output:
  - platform: gpio
    id: relay_1
    pin: GPIO12

fan:
  - platform: binary
    id: fan_1
    name: None
    on_turn_off:
    - light.turn_off: status_1
    on_turn_on:
    - light.turn_on: status_1
    output: relay_1
    restore_mode: ALWAYS_OFF

<<: !include ../common/common-8266.yaml
