---
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO1
      mode: INPUT_PULLUP
      inverted: True
    name: "${friendly_name} Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "${friendly_name} Status"

sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s
  - platform: hlw8012
    current_resistor: ${current_resistor}
    voltage_divider: ${voltage_divider}
    sel_pin: GPIO12
    cf_pin: GPIO4
    cf1_pin: GPIO5
    update_interval: 30s
    initial_mode: voltage
    change_mode_every: 8
    current:
      name: "${friendly_name} Current"
      accuracy_decimals: 2
      filters:
        - throttle_average: 30s
        - multiply: ${current_multiply}
    voltage:
      name: "${friendly_name} Voltage"
      accuracy_decimals: 2
      filters:
        - throttle_average: 30s
    power:
      name: "${friendly_name} Power"
      accuracy_decimals: 2
      id: my_power
      filters:
        - throttle_average: 30s
    energy:
      name: "${friendly_name} Energy"
      accuracy_decimals: 2
      filters:
        - throttle: 30s
    # apparent_power: #(only available with version 2024.3.0 or greater)
    #   name: "${friendly_name} Apparent Power"
    #   filters:
    #     - throttle_average: 60s
    # power_factor: #(only available with version 2024.3.0 or greater)
    #   name: "${friendly_name} Power Factor"
    #   accuracy_decimals: 2
    #   filters:
    #     - throttle_average: 60s

  - platform: total_daily_energy #(Optional, not specific to cse7766)
    name: "${friendly_name} Daily Energy"
    power_id: my_power
    accuracy_decimals: 2

switch:
  - platform: gpio
    name: "${friendly_name}"
    pin: GPIO14
    id: relay
    restore_mode: ALWAYS_ON

status_led:
  pin:
    number: GPIO13
    inverted: True
