# This device needs to be broken open and manually flashed.
---
substitutions:
  name: unused-5e
  friendly_name: Unused 5E
  ip_address: 10.3.2.60
  voltage_divider: "2069.986759838176" #Calibrated on 2025-03-16
  current_resistor: "0.002372161940866017" #New values via calculator at https://esphome.io/components/sensor/hlw8012.html
  current_multiply: "1.007049880556328"

packages:
  power-monitor: !include devices/w-us002s-power-monitor.yaml

# esphome:
#   area: 'office'
