---
substitutions:
  name: 3dprinter
  friendly_name: 3d Printer
  ip_address: 10.3.2.17
  current_multiply: "1.0"
  current_resistor: "0.001"
  voltage_divider: "2351"

packages:
  power-monitor: !include devices/w-us002s.yaml

esphome:
  area: 'office'
