# Sensorbox v2 config for PCB SBR1
# config r2 (20241130)
# https://go.toms3d.org/sbr1
# Leave the "substitutions" block in place, then add this config.
# You can choose a new "friendly name" in the substitutions, this will be its display name in Home Assistant.
---
substitutions:
  name: printer-air-sensor
  friendly_name: Printer Air Sensor
  ip_address: 10.3.2.22
  # web_server_version: "2"
  display_heading_1: "Farticles"

packages:
  printer_air_sensor: !include devices/air-sensor-v2-pms5003s.yaml
  # web: !include common/web-server.yaml
