---
substitutions:
  name: printer-air-sensor
  friendly_name: Printer Air Sensor
  ip_address: 10.3.2.22
  display_heading_1: "Farticles"

packages:
  advanced_air_sensor: !include devices/air-sensor-v2-pms5003s.yaml

esphome:
  area: 'office'
