---
substitutions:
  name: austins-gaming-computer
  friendly_name: Austins Gaming Computer
  ip_address: 10.3.2.82

packages:
  power-monitor: !include devices/sonoff-s31-power-monitor.yaml

esphome:
  area: 'basement'
