---
substitutions:
  name: basement-stair-lights-secondary
  friendly_name: Control Basement Stair Lights Secondary
  ip_address: 10.3.2.151
  hass_event_name: esphome.3way_basement_stair_lights_button
  relay_pin: GPIO4 # Black hole, this is just a control switch.  Don't need the relay "clicking" on.
  mdi_icon: 'mdi:candle'

packages:
  switch: !include devices/3way-gosund-ks-602s-light-switch.yaml

esphome:
  area: 'basement'
