# Basic Config
---
substitutions:
  name: blower
  friendly_name: Blower
  ip_address: 10.3.2.19
  esp8266_board: sonoff_basic

packages:
  api: !include common/api.yaml
  common-elements: !include common/common-elements.yaml
  common-esp8266: !include common/common-esp8266.yaml
  esphome: !include common/esphome.yaml
  logger: !include common/logger.yaml
  ota: !include common/ota.yaml
  time: !include common/time.yaml
  web: !include common/web-server.yaml
  wifi: !include common/wifi.yaml

# Device Specific Config
binary_sensor:
  - platform: gpio
    id: push_button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    internal: true
    on_press:
      # Prevents unintended LED lit states.
      if:
        condition:
          - fan.is_off: fan_1
        then:
          - light.turn_on: blue_led
          - fan.turn_on: fan_1
        else:
          - fan.turn_off: fan_1

light:
  - platform: status_led
    disabled_by_default: true
    id: blue_led
    internal: true
    name: "Status LED"
    pin:
      inverted: true
      number: GPIO13

output:
  - platform: gpio
    id: relay_1
    pin: GPIO12

fan:
  - platform: binary
    id: fan_1
    name: None
    on_turn_off:
      if:
        condition:
          - light.is_on: blue_led
        then:
          - light.turn_off: blue_led
    on_turn_on:
      if:
        condition:
          - light.is_off: blue_led
        then:
          - light.turn_on: blue_led
    output: relay_1
    restore_mode: ALWAYS_OFF
