---
substitutions:
  name: cold-storage-light
  friendly_name: Cold Storage Lights
  ip_address: 10.3.2.74
  off_timer_scope: light
  off_timer_device: light_1
  off_timer_minutes: "/15"

packages:
  switch: !include devices/gosund-ks-602s-light-switch.yaml
  15-minute-off: !include common/timers/minute-eventing-off-timer.yaml

esphome:
  area: 'cold storage'
