---
substitutions:
  name: douglas-lights
  friendly_name: Douglas Lights
  ip_address: 10.3.2.58
  voltage_divider: "2069.986759838176" #Calibrated on 2025-03-16
  current_resistor: "0.002372161940866017" #New values via calculator at https://esphome.io/components/sensor/hlw8012.html
  current_multiply: "1.007049880556328"
  decoration_timer_scope: switch
  decoration_timer_device: relay

packages:
  power-monitor: !include devices/w-us002s.yaml
  daily-timer: !include common/timers/decorations.yaml

# esphome:
#   area: 'office'
