---
substitutions:
  name: electric-fence
  friendly_name: Electric Fence
  ip_address: 10.3.2.99
  on_timer_minutes: "/30"
  device_restore_mode: "ALWAYS_ON"
  mdi_icon: mdi:fence-electric

packages:
  fence: !include devices/sonoff-basic-r2-switch-mdi.yaml
  every-30-minute-on: !include common/timers/minute-eventing-on-timer.yaml

esphome:
  area: 'outside'
