---
substitutions:
  name: end-table
  friendly_name: End Table
  ip_address: 10.3.2.112
  daily_timer_scope: light
  daily_timer_device: light_1
  mdi_icon: 'mdi:lamp'

packages:
  switch: !include devices/sonoff-basic-r2.yaml
  daily-timer: !include common/timers/daily-timer.yaml

esphome:
  area: 'main'
