---
substitutions:
  name: end-table
  friendly_name: End Table
  ip_address: 10.3.2.112
  decoration_timer_scope: light
  decoration_timer_device: light_1

packages:
  switch: !include devices/sonoff-basic-r2.yaml
  daily-timer: !include common/timers/daily-timer.yaml

esphome:
  area: 'main'
