---
substitutions:
  name: entry-decor
  friendly_name: Entry Decor
  ip_address: 10.3.2.113
  daily_timer_scope: light
  daily_timer_device: light_1
  mdi_icon: 'mdi:candle'

packages:
  switch: !include devices/sonoff-basic-r2.yaml
  daily-timer: !include common/timers/daily-timer.yaml

esphome:
  area: 'entry'
