---
substitutions:
  name: entry-chandelier
  friendly_name: Entry Chandelier
  ip_address: 10.3.2.124
  mdi_icon: 'mdi:chandelier'

packages:
  light: !include devices/gosund-ks-602s-light-switch.yaml

esphome:
  area: 'Entry'
