---
substitutions:
  name: exterior-side-lights
  friendly_name: Exterior Side Lights
  ip_address: 10.3.2.125
  mdi_icon: 'mdi:outdoor-lamp'

packages:
  light: !include devices/gosund-ks-602s-light-switch.yaml

esphome:
  area: 'outside'
