substitutions:
  ip_address: 10.3.2.122
  name: family-dimmer
  friendly_name: Family Dimmer
  mdi_icon: 'mdi:light-recessed'

packages:
  feit_dimmer_esp8266: !include devices/feit-dimmer-esp8266.yaml

esphome:
  area: 'main'
