---
substitutions:
  name: fireplace
  friendly_name: Fireplace
  ip_address: 10.3.2.20
  mdi_icon: mdi:fire

packages:
  fireplace: !include devices/sonoff-basic-r2-switch-mdi.yaml

esphome:
  area: 'main'
