---
substitutions:
  name: garage-lights-secondary
  friendly_name: Control Garage Lights Secondary
  ip_address: 10.3.2.136
  hass_event_name: esphome.3way_garage_lights_button
  relay_pin: GPIO4 # Black hole, this is just a control switch.  Don't need the relay "clicking" on.
  mdi_icon: 'mdi:spotlight'

packages:
  switch: !include devices/3way-gosund-ks-602s-light-switch.yaml

esphome:
  area: 'garage'
