---
substitutions:
  id_prefix: third_car_gdo
  name: third-car-garage
  friendly_name: Third Car Garage
  ip_address: 10.3.2.24

packages:
  ratgdo: !include devices/ratgdo-25i.yaml

esphome:
  area: 'garage'
