---
substitutions:
  id_prefix: greenhouse
  name: greenhouse
  friendly_name: Greenhouse Monitor
  ip_address: 10.3.2.34

packages:
  wemod1-bme280: !include devices/wemod1-bme280.yaml
  button-factory-reset: !include common/buttons/factory-reset.yaml
