---
substitutions:
  name: holiday-stairs
  friendly_name: Holiday Stairs
  ip_address: 10.3.2.114
  mdi_icon: 'mdi:string-lights'

packages:
  switch: !include devices/sonoff-basic-r2-switch-mdi.yaml
  daily-timer: !include common/timers/daily-timer.yaml

esphome:
  area: 'entry'
