---
substitutions:
  name: internet-router
  friendly_name: Internet Router
  ip_address: 10.3.2.85
  device_restore_mode: "ALWAYS_ON"

packages:
  switch: !include devices/sonoff-basic-r2-with-bme280-as-switch.yaml
  cron-on: !include common/timers/cron-eventing-on-timer.yaml

esphome:
  area: 'utility'
