---
substitutions:
  name: kids-shower-lights
  friendly_name: Kids Shower Lights
  ip_address: 10.3.2.106

packages:
  light: !include devices/maxcio-light-switch.yaml

esphome:
  area: 'kids bathroom'
