---
substitutions:
  name: kids-toilet-lights
  friendly_name: Kids Toilet Lights
  ip_address: 10.3.2.107
  status_led_on_turn_off_action: "light.turn_on"

packages:
  light: !include devices/maxcio-light-switch.yaml

esphome:
  area: 'kids bathroom'
