---
substitutions:
  name: kitchen-sink-lights-secondary
  friendly_name: Control Kitchen Sink Lights Secondary
  ip_address: 10.3.2.93
  hass_event_name: esphome.3way_kitchen_sink_lights_button
  relay_pin: GPIO4 # Black hole, this is just a control switch.  Don't need the relay "clicking" on.
  mdi_icon: 'mdi:ceiling-light'

packages:
  switch: !include devices/3way-gosund-ks-602s-light-switch.yaml

esphome:
  area: 'kitchen'
