---
substitutions:
  name: kitchen-range-hood
  friendly_name: Kitchen Range Hood
  ip_address: 10.3.2.87
  device_restore_mode: "ALWAYS_ON"
  mdi_icon: 'mdi:wall-sconce-flat'

packages:
  switch: !include devices/sonoff-basic-r2-with-bme280.yaml

esphome:
  area: 'Kitchen'
