---
substitutions:
  name: kitchen-can-lights
  friendly_name: Kitchen Can Lights
  ip_address: 10.3.2.90
  hass_event_name: esphome.3way_kitchen_can_lights_button
  mdi_icon: 'mdi:light-recessed'

packages:
  switch: !include devices/3way-gosund-ks-602s-light-switch.yaml

esphome:
  area: 'Kitchen'
