---
substitutions:
  name: laundry-room-lights
  friendly_name: Laundry Room Lights
  ip_address: 10.3.2.142

packages:
  switch: !include devices/gosund-ks-602s-light-switch.yaml

esphome:
  area: 'laundry'
