---
substitutions:
  name: library-lights
  friendly_name: Library Lights
  ip_address: 10.3.2.37
  mdi_icon: 'mdi:dome-light'

packages:
  light: !include devices/gosund-ks-602s-light-switch.yaml

esphome:
  area: library
