---
substitutions:
  name: lilys-hall-lights-tertiary
  friendly_name: Control Lilys Hall Lights Tertiary
  ip_address: 10.3.2.139
  hass_event_name: esphome.3way_lilys_hall_lights_button
  relay_pin: GPIO4 # Black hole, this is just a control switch.  Don't need the relay "clicking" on.
  mdi_icon: 'mdi:dome-light'

packages:
  switch: !include devices/3way-gosund-ks-602s-light-switch.yaml

esphome:
  area: 'upstairs hallway'
