---
substitutions:
  name: lilys-fan
  friendly_name: Lilys Fan
  ip_address: 10.3.2.97
  device_class: fan
  on_timer_scope: fan
  on_timer_device: fan_1
  on_timer_minutes: "/30"
  device_restore_mode: "ALWAYS_ON"

packages:
  switch: !include devices/sonoff-basic-r2.yaml
  every-30-minute-on: !include common/timers/minute-eventing-on-timer.yaml

esphome:
  area: 'lily'
