---
substitutions:
  name: main-hall-tertiary
  friendly_name: Control Main Hall Tertiary
  ip_address: 10.3.2.40
  hass_event_name: esphome.3way_main_hall_lights_button
  relay_pin: GPIO4 # Black hole, this is just a control switch.  Don't need the relay "clicking" on.

packages:
  switch: !include devices/3way-gosund-ks-602s-light-switch.yaml

esphome:
  area: 'main'
