---
substitutions:
  name: main-hall-lights
  friendly_name: Main Hall Lights
  ip_address: 10.3.2.33
  hass_event_name: esphome.3way_main_hall_lights_button

packages:
  switch: !include devices/3way-gosund-ks-602s-light-switch.yaml

esphome:
  area: 'main'
