---
substitutions:
  name: mantle-decor
  friendly_name: Mantle Decor
  ip_address: 10.3.2.119
  daily_timer_scope: light
  daily_timer_device: light_1
  mdi_icon: 'mdi:string-lights'

packages:
  switch: !include devices/sonoff-basic-r2.yaml
  daily-timer: !include common/timers/daily-timer.yaml

esphome:
  area: 'main'
