---
substitutions:
  name: office-desk
  friendly_name: Office Desk
  ip_address: 10.3.2.69
  voltage_divider: "2069.986759838176" #Calibrated on 2025-03-16
  current_resistor: "0.002372161940866017" #New values via calculator at https://esphome.io/components/sensor/hlw8012.html
  current_multiply: "1.007049880556328"
  mdi_icon: 'mdi:desktop-tower-monitor'

packages:
  power-monitor: !include devices/w-us002s-power-monitor.yaml

esphome:
  area: 'Office'
