---
substitutions:
  name: pet-lights
  friendly_name: Pet Lights
  ip_address: 10.3.2.41
  mdi_icon: 'mdi:wall-sconce-flat'

packages:
  power-monitor: !include devices/sonoff-s31-power-monitor.yaml
  sun-timer: !include common/timers/sun.yaml

esphome:
  area: 'austins room'
