---
substitutions:
  name: pet-lights
  friendly_name: Pet Lights
  ip_address: 10.3.2.41

packages:
  power-monitor: !include devices/sonoff-s31-power-monitor.yaml
  daily-timer: !include common/timers/daily-timer.yaml

esphome:
  area: 'austins room'
