---
substitutions:
  name: pi-hole
  friendly_name: Pi-Hole
  ip_address: 10.3.2.86
  device_restore_mode: "ALWAYS_ON"

packages:
  switch: !include devices/sonoff-basic-r2-with-bme280-as-switch.yaml
  every-minute-on: !include common/timers/minute-eventing-on-timer.yaml

esphome:
  area: 'utility'
