---
substitutions:
  name: powder-lights
  friendly_name: Powder Lights
  ip_address: 10.3.2.109
  mdi_icon: 'mdi:vanity-light'

packages:
  light: !include devices/maxcio-light-switch.yaml

esphome:
  area: 'powder bathroom'
