---
substitutions:
  name: powder-fan
  friendly_name: Powder Fan
  ip_address: 10.3.2.154
  device_class: fan
  mdi_icon: 'mdi:fan'

packages:
  switch: !include devices/gosund-ks-602s-light-switch.yaml

esphome:
  area: 'Powder'
