---
substitutions:
  name: printer-bento-box
  friendly_name: Printer Bento Box
  ip_address: 10.3.2.94
  device_class: 'fan'

packages:
  switch: !include devices/sonoff-basic-r2.yaml

esphome:
  area: 'office'
