---
substitutions:
  name: right-mantle
  friendly_name: Right Mantle
  ip_address: 10.3.2.117
  daily_timer_scope: light
  daily_timer_device: light_1
  mdi_icon: 'mdi:string-lights'

packages:
  switch: !include devices/sonoff-basic-r2.yaml
  daily-timer: !include common/timers/daily-timer.yaml

esphome:
  area: 'Family'
