---
substitutions:
  name: study-lights
  friendly_name: Study Lights
  ip_address: 10.3.2.36
  # hass_service_to_control1: switch
  # hass_entity_to_control1: main_hall_second_main_hall_secondary

packages:
  light: !include devices/3way-maxcio-switch-as-light.yaml

esphome:
  area: 'study'
