---
substitutions:
  name: study-air-sensor
  friendly_name: Study Air Sensor
  ip_address: 10.3.2.23
  display_heading_1: "Farticles"

packages:
  air_sensor: !include devices/air-sensor-v2-pms5003.yaml

esphome:
  area: 'study'
