---
substitutions:
  name: study-lights
  friendly_name: Study Lights
  ip_address: 10.3.2.36
  # relay_pin: GPIO4 # Black hole, this is just a control switch.  Don't need the relay clicking on.
  # led_link_pin: GPIO1
  # status_led_pin: GPIO16 #Green when engaged
  # hass_service_to_control1: switch
  # hass_entity_to_control1: main_hall_second_main_hall_secondary

packages:
  study_lights: !include devices/3way-maxcio-switch-as-light.yaml
