---
substitutions:
  name: unused-e1
  friendly_name: Unused E1
  ip_address: 10.3.2.87

packages:
  switch: !include devices/sonoff-basic-r2-with-bme280-as-switch.yaml

# esphome:
#   area: 'office'
