substitutions:
  off_timer_scope: switch
  off_timer_device: relay_1
  off_timer_seconds: "0"
  off_timer_minutes: "/15"
  off_timer_hours: "*"

time:
  - platform: sntp
    timezone: !secret time_zone
    on_time:
      - seconds: ${off_timer_seconds}
        minutes: ${off_timer_minutes}
        hours: ${off_timer_hours}
        then:
          - ${off_timer_scope}.turn_off: ${off_timer_device}

      # # Cron syntax
      # - cron: '${off_timer_seconds} ${off_timer_minutes} * * * *'
      #   then:
      #     - ${off_timer_scope}.turn_off: ${off_timer_device}
