substitutions:
  daily_timer_scope: switch
  daily_timer_device: relay_1
  daily_timer_on_hour: "7"
  daily_timer_off_hour: "23"

time:
  - platform: sntp
    timezone: !secret time_zone
    on_time:
      # Turn on my_switch at 7:00 AM
      - seconds: 0
        minutes: 0
        hours: ${daily_timer_on_hour}
        then:
          - ${daily_timer_scope}.turn_on: ${daily_timer_device}

      # Turn off my_switch at 11:00 PM
      - seconds: 0
        minutes: 0
        hours: ${daily_timer_off_hour}
        then:
          - ${daily_timer_scope}.turn_off: ${daily_timer_device}
