---
substitutions:
  api_reboot_timeout: 15min

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

ota:
  - platform: esphome
    password: !secret ota_password

api:
  reboot_timeout: $api_reboot_timeout
  encryption:
    key: !secret api_encryption_key

web_server:
  include_internal: true
  port: 80
  version: 3
  auth:
    username: !secret web_username
    password: !secret web_password

logger:

time:
  - platform: sntp
    id: sntp_time
    timezone: !secret time_zone
    servers:
      - !secret sntp_server

binary_sensor: !include_dir_list common/binary_sensors
button: !include_dir_list common/buttons
sensor: !include_dir_list common/sensors
