---
substitutions:
  esp8266_restore_from_flash: False
  esp8266_early_pin_init: False

esp8266:
  board: ${esp8266_board} #Required, not defaulting.
  framework:
    version: recommended
  restore_from_flash: ${esp8266_restore_from_flash}
  early_pin_init: ${esp8266_early_pin_init}
