---
substitutions:
  wifi_reboot_timeout: 15min
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    password: !secret fallback_ap_password
  manual_ip:
    static_ip: $ip_address
    gateway: !secret gateway
    subnet: !secret subnet
    dns1: !secret dns1
    dns2: !secret dns2
  reboot_timeout: ${wifi_reboot_timeout}

captive_portal:
