---
substitutions:
  esp8266_restore_from_flash: "False"
  esp8266_early_pin_init: "False"
  esp8266_store_log_strings_in_flash: "true"

packages:
  sensors-debug: !include sensors/debug-esp8266.yaml

esp8266:
  board: ${esp8266_board} #Required, not defaulting.
  framework:
    version: recommended
  restore_from_flash: ${esp8266_restore_from_flash}
  early_pin_init: ${esp8266_early_pin_init}

logger:
  esp8266_store_log_strings_in_flash: ${esp8266_store_log_strings_in_flash}
  # default is true, uses more memory when false
