---
substitutions:
  esp8266_board: esp01_1m
  physical_button_pin: GPIO00
  relay_pin: GPIO12
  status_led_pin: GPIO13

packages:
  api: !include ../common/api.yaml
  common-elements: !include ../common/common-elements.yaml
  common-esp8266: !include ../common/common-esp8266.yaml
  esphome: !include ../common/esphome.yaml
  logger: !include ../common/logger.yaml
  ota: !include ../common/ota.yaml
  time: !include ../common/time.yaml
  web: !include ../common/web-server.yaml
  wifi: !include ../common/wifi.yaml

light:
  - platform: status_led
    disabled_by_default: true
    id: status_1
    internal: true
    name: "Status LED"
    pin:
      inverted: true
      number: ${status_led_pin}

binary_sensor:
  - platform: gpio
    filters:
      - delayed_off: 10ms
      - invert:
    id: button_1
    internal: true
    name: Button
    on_press:
      - fan.toggle: fan_1
    pin: ${physical_button_pin}

output:
  - platform: gpio
    id: relay_1
    pin: ${relay_pin}

fan:
  - platform: binary
    id: fan_1
    name: None
    on_turn_off:
    - light.turn_off: status_1
    on_turn_on:
    - light.turn_on: status_1
    output: relay_1
    restore_mode: ALWAYS_OFF
