---
substitutions:
  esp8266_board: esp01_1m
  physical_button_pin: GPIO00
  relay_pin: GPIO12
  status_led_pin: GPIO13
  device_class: light
  button_as_internal: "true"
  device_restore_mode: "ALWAYS_OFF"

packages:
  api: !include ../common/api.yaml
  common-elements: !include ../common/common-elements.yaml
  common-esp8266: !include ../common/common-esp8266.yaml
  esphome: !include ../common/esphome.yaml
  logger: !include ../common/logger.yaml
  ota: !include ../common/ota.yaml
  time: !include ../common/time.yaml
  web: !include ../common/web-server.yaml
  wifi: !include ../common/wifi.yaml

binary_sensor:
  - platform: gpio
    filters:
      - delayed_off: 10ms
      - invert:
    id: button_1
    internal: ${button_as_internal}
    name: Button
    on_press:
      - ${device_class}.toggle: ${device_class}_1
    pin: ${physical_button_pin}

${device_class}:
  - platform: binary
    id: ${device_class}_1
    name: None
    icon: ${mdi_icon}
    on_turn_off:
      - light.turn_off: status_1
    on_turn_on:
      - light.turn_on: status_1
    output: relay_1
    restore_mode: ${device_restore_mode}

light:
  - platform: status_led
    disabled_by_default: true
    id: status_1
    internal: true
    name: "Status LED"
    pin:
      inverted: true
      number: ${status_led_pin}

output:
  - platform: gpio
    id: relay_1
    pin: ${relay_pin}
