# Basic Config
---
substitutions:
  esp8266_board: sonoff_basic
  physical_button_pin: GPIO0
  relay_pin: GPIO12
  status_led_pin: GPIO13
  device_class: light
  button_as_internal: "true"
  device_restore_mode: "ALWAYS_OFF"

packages:
  api: !include ../common/api.yaml
  common-elements: !include ../common/common-elements.yaml
  common-esp8266: !include ../common/common-esp8266.yaml
  esphome: !include ../common/esphome.yaml
  logger: !include ../common/logger.yaml
  ota: !include ../common/ota.yaml
  time: !include ../common/time.yaml
  web: !include ../common/web-server.yaml
  wifi: !include ../common/wifi.yaml

binary_sensor:
  - platform: gpio
    id: button_1
    name: "Button"
    pin:
      number: ${physical_button_pin}
      mode: INPUT_PULLUP
      inverted: True
    internal: ${button_as_internal}
    on_press:
      - ${device_class}.toggle: ${device_class}_1

${device_class}:
  - platform: binary
    id: ${device_class}_1
    name: None
    on_turn_off:
      - light.turn_off: blue_led
    on_turn_on:
      - light.turn_on: blue_led
    output: relay_1
    restore_mode: ${device_restore_mode}

light:
  - platform: status_led
    disabled_by_default: true
    id: blue_led
    internal: true
    name: "Status LED"
    pin:
      inverted: true
      number: ${status_led_pin}

output:
  # The relay switches on the red side of the LED when active.
  - platform: gpio
    pin: ${relay_pin}
    id: relay_1
