# Basic Config
---
substitutions:
  esp8266_board: sonoff_basic
  physical_button_pin: GPIO0
  relay_pin: GPIO12
  status_led_pin: GPIO13

packages:
  api: !include ../common/api.yaml
  common-elements: !include ../common/common-elements.yaml
  common-esp8266: !include ../common/common-esp8266.yaml
  esphome: !include ../common/esphome.yaml
  logger: !include ../common/logger.yaml
  ota: !include ../common/ota.yaml
  time: !include ../common/time.yaml
  web: !include ../common/web-server.yaml
  wifi: !include ../common/wifi.yaml

# Device Specific Config
binary_sensor:
  - platform: gpio
    id: button_1
    name: "Button"
    pin:
      number: ${physical_button_pin}
      mode: INPUT_PULLUP
      inverted: True
    internal: true
    on_press:
      - switch.toggle: relay
  - platform: binary
    id: light_1
    name: None
    on_turn_off:
    - light.turn_off: status_1
    on_turn_on:
    - light.turn_on: status_1
    output: relay_1
    restore_mode: ALWAYS_OFF

output:
  - platform: gpio
    id: relay_1
    pin: ${relay_pin}


light:
  - platform: status_led
    id: blue_led
    internal: True
    pin:
      number: ${status_led_pin}
      inverted: True

switch:
  # The relay switches on the red side of the LED when active.
  - platform: gpio
    name: "Sonoff Basic Relay"
    pin: ${relay_pin}
    id: relay
    on_turn_off:
      - light.turn_off: blue_led
    on_turn_on:
      - light.turn_on: blue_led
