# Basic Config
---
substitutions:
  esp8266_board: sonoff_basic
  physical_button_pin: GPIO0
  relay_pin: GPIO12
  status_led_pin: GPIO13

packages:
  api: !include ../common/api.yaml
  common-elements: !include ../common/common-elements.yaml
  common-esp8266: !include ../common/common-esp8266.yaml
  esphome: !include ../common/esphome.yaml
  logger: !include ../common/logger.yaml
  ota: !include ../common/ota.yaml
  time: !include ../common/time.yaml
  web: !include ../common/web-server.yaml
  wifi: !include ../common/wifi.yaml

# Device Specific Config
binary_sensor:
  - platform: gpio
    id: push_button
    pin:
      number: ${physical_button_pin}
      mode: INPUT_PULLUP
      inverted: True
    internal: true
    on_press:
      # Prevents unintended LED lit states.
      if:
        condition:
          - switch.is_off: ${name}_relay
        then:
          - light.turn_on: blue_led
          - switch.turn_on: ${name}_relay
        else:
          - switch.turn_off: ${name}_relay

light:
  - platform: status_led
    id: blue_led
    internal: True
    pin:
      number: ${status_led_pin}
      inverted: True

switch:
  # The relay switches on the red side of the LED when active.
  - platform: gpio
    name: ''
    pin: ${relay_pin}
    icon: ${mdi_icon}
    id: ${name}_relay
    on_turn_off:
      if:
        condition:
          - light.is_on: blue_led
        then:
          - light.turn_off: blue_led
