# Review https://devices.esphome.io/devices/BlitzWolf-BW-SHP2-Power-Monitoring-Plug

---
substitutions:
  physical_button_pin: GPIO1
  sel_pin: GPIO12
  cf_pin: GPIO4
  cf1_pin: GPIO5
  relay_pin: GPIO14
  green_led_pin: GPIO3 #WiFi LED
  blue_led_pin: GPIO13 #Button LED
  voltage_divider: "2069.986759838176" #Calibrated on 2025-03-16 on ec:fa:bc:89:a8:b3
  current_resistor: "0.002372161940866017" #New values via calculator at https://esphome.io/components/sensor/hlw8012.html
  current_multiply: "1.007049880556328"
  # current_multiply: "1.0" # Defaults from HLW8012
  # current_resistor: "0.001" # Defaults from HLW8012
  # voltage_divider: "2351" # Defaults from HLW8012
  esp8266_board: esp01_1m
  device_restore_mode: "ALWAYS_ON" # Powering the relay may cause damage or instability when the programmer is supplying Vcc.
  button_as_internal: "true"

packages:
  api: !include ../common/api.yaml
  common-elements: !include ../common/common-elements.yaml
  common-esp8266: !include ../common/common-esp8266.yaml
  esphome: !include ../common/esphome.yaml
  logger: !include ../common/logger.yaml
  ota: !include ../common/ota.yaml
  time: !include ../common/time.yaml
  web: !include ../common/web-server.yaml
  wifi: !include ../common/wifi.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: ${physical_button_pin}
      mode: INPUT_PULLUP
      inverted: True
    internal: ${button_as_internal}
    name: Button
    on_press:
      - switch.toggle: relay_1

output:
- platform: esp8266_pwm
  id: blue_led
  pin:
    number: ${blue_led_pin}
    inverted: True

sensor:
  - platform: hlw8012
    current_resistor: ${current_resistor}
    voltage_divider: ${voltage_divider}
    sel_pin: ${sel_pin}
    cf_pin: ${cf_pin}
    cf1_pin: ${cf1_pin}
    initial_mode: voltage
    change_mode_every: 3
    update_interval: 3s
    current:
      name: "Current"
      accuracy_decimals: 2
      filters:
        - throttle_average: 30s
        - multiply: ${current_multiply}
        # - calibrate_linear: # From https://esphome.io/components/sensor/index.html#calibrate-linear
        #   - 0.0 -> 0.013
        #   - 0.08208 -> 0.071
        #   - 1.34223 -> 1.066
        #   - 5.57170 -> 4.408
        #   - 6.69184 -> 5.259
        #   - 6.97187 -> 5.540
    voltage:
      name: "Voltage"
      accuracy_decimals: 2
      filters:
        - throttle_average: 30s
        # # Map from sensor -> measured value
        # - calibrate_linear: # From https://esphome.io/components/sensor/index.html#calibrate-linear
        #     - 0.0 -> 0.0
        #     - 602.87506 -> 229.9
        #     - 609.8 -> 232.8
    power:
      name: "Power"
      accuracy_decimals: 2
      id: my_power
      filters:
        - throttle_average: 30s
          # - calibrate_linear: # From https://esphome.io/components/sensor/index.html#calibrate-linear
          #   - 0.0 -> 1.14
          #   - 62.06167 -> 10.93
          #   - 1503.27161 -> 247.6
          #   - 1599.81213 -> 263.7
          #   - 3923.67700 -> 631.4
          #   - 7109.50928 -> 1148.0
          #   - 7237.0857 -> 1193.0
          #   - 7426.71338 -> 1217.0
    energy:
      name: "Energy"
      accuracy_decimals: 2
      filters:
        - throttle: 30s
        - multiply: 0.001
      unit_of_measurement: kWh

  - platform: integration
    name: 'Total Energy'
    sensor: my_power
    time_unit: h
    restore: true
    state_class: total_increasing
    device_class: energy
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh

status_led:
  pin:
    number: ${green_led_pin}
    inverted: True

switch:
  - platform: gpio
    name: "${friendly_name}"
    pin: ${relay_pin}
    id: relay_1
    restore_mode: ${device_restore_mode}
